

trigger: none


stages:
- stage: Build
  displayName: Build and Push an image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
 
    steps:
    - task: Bash@3
      displayName: Build an image
      inputs:
        targetType: 'inline'
        script: |-
          cd $(Build.SourcesDirectory)/application/
          docker build . -t $(LOGIN)/$(IMAGE_NAME):$(Build.BuildId)

    - task: Bash@3
      displayName: Login to DockerHub
      inputs:
        targetType: 'inline'
        script: docker login --username "$(LOGIN)" --password "$(PSWD)"
    - task: Bash@3
      displayName: Push an image
      inputs:
        targetType: 'inline'
        script: docker push $(LOGIN)/$(IMAGE_NAME):$(Build.BuildId)
  